In [3]:
import numpy as np 
arr = np.array([[1, 2, 3, 4, 5, 6, 7],
                [8, 9, 10, 11, 12, 13, 14]])

In [4]:
arr[1, 5]

13

In [6]:
# Using Neg.Number
arr[1, -2]

13

In [7]:
# Getting one entire Row
arr[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
# Getting one entire Column
arr[:, 2]

array([ 3, 10])

In [10]:
# Syntax
# [StartIndex:EndIndex:StepSize]
arr[0, 1:-1:2]

array([2, 4, 6])

In [11]:
arr[1, 2] = 20

In [12]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 20, 11, 12, 13, 14]])

In [17]:
sec_arr = np.array([[[1, 2],
                     [3, 4]],
                     [[5, 6],
                     [7, 8]]])

In [14]:
sec_arr[0, 1, 1]

4

In [19]:
sec_arr[:, 1, :] = [[9, 8], [7, 6]]

In [20]:
sec_arr

array([[[1, 2],
        [9, 8]],

       [[5, 6],
        [7, 6]]])

In [23]:
demo_arr = np.zeros((4, 2, 1), dtype="int8")
demo_arr_1 = np.ones((2, 2), dtype="int8")

In [28]:
demo_arr_f = np.full((2, 2), 99)
demo_arr_f

array([[99, 99],
       [99, 99]])

In [26]:
np.full_like(sec_arr, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [29]:
np.random.rand(4, 2)

array([[0.02713959, 0.63667601],
       [0.80154108, 0.75395704],
       [0.11125932, 0.8519137 ],
       [0.79563114, 0.70544729]])

In [34]:
np.random.randint(50, size=(3, 3))

array([[23,  2, 24],
       [ 4, 32, 14],
       [41, 18, 34]])

In [35]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
repeat_arr = np.array([[1, 2, 3]]).repeat(3)

In [37]:
repeat_arr

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [41]:
repeat_arr = np.array([[1, 2, 3]]).repeat(3, axis=0)

In [42]:
repeat_arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [44]:
output = np.ones((5, 5))

In [49]:
zeroout = np.zeros((3, 3))
zeroout[1, 1] = 9
output[1:4, 1:4] = zeroout
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])