In [1]:
import numpy as np

In [10]:
raw_arr = np.random.randint(0, 1000, size=4)

In [11]:
raw_arr

array([568, 241, 760, 167])

In [12]:
raw_arr + 2

array([570, 243, 762, 169])

In [13]:
raw_arr - 5

array([563, 236, 755, 162])

In [14]:
raw_arr / 2

array([284. , 120.5, 380. ,  83.5])

In [15]:
raw_arr * 4

array([2272,  964, 3040,  668])

In [18]:
raw_arr + np.random.randint(0, 1000, size=4)

array([1455, 1038, 1202, 1113])

In [19]:
np.cos(raw_arr)

array([-0.80904534, -0.61954428,  0.96498184, -0.87968859])

In [20]:
la_arr = np.ones((2, 3))
lb_arr = np.full((3, 2), 2)

In [21]:
np.matmul(la_arr, lb_arr)

array([[6., 6.],
       [6., 6.]])