In [1]:
import numpy as np

In [5]:
stat = np.array([[np.random.randint(0, 1000, size=4)],
                [np.random.randint(0, 1000, size=4)]])

In [6]:
stat

array([[[729,  47, 299, 484]],

       [[616, 991, 414, 578]]])

In [7]:
np.min(stat)

47

In [8]:
np.max(stat)

991

In [9]:
np.min(stat, axis=0)

array([[616,  47, 299, 484]])

In [11]:
np.max(stat, axis=1)

array([[729,  47, 299, 484],
       [616, 991, 414, 578]])

In [12]:
stat.sum()

4158

In [14]:
stat.max(axis=1)

array([[729,  47, 299, 484],
       [616, 991, 414, 578]])